name: First Workflow
on: push

jobs:
  runs-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js v20
        run: nvm install 20
      - name: Check node version
        run: node -v
