name: First Workflow
on: push

jobs:
  runs-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display some text
        run: echo "Some Text"
      - name: Run multiple commands
        run: |
          node -v
          npm -v
