name: First Workflow
on: push

jobs:
  runs-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Install nvm
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
      - name: Install Node.js v20
        run: nvm install 20
      - name: Check node version
        run: node -v
